<template>
  <div class="business-page">
    <header class="page-head"><div class="page-title"><h1>销售入单</h1><p>完整记录客户、合同、收款、服务目标和承诺风险。</p></div><div class="head-actions"><button class="outline-button">保存草稿</button><button class="primary-button">提交审核</button></div></header>
    <div class="steps"><div class="step" :class="{active:i<2}" v-for="(s,i) in steps" :key="s"><span>{{ i+1 }}</span>{{ s }}</div></div>
    <div class="content-grid" style="grid-template-columns:minmax(0,2.35fr) minmax(300px,1fr)">
      <section class="panel form-panel"><h2 class="section-title">客户基本信息</h2><p class="section-help">请填写客户的基本资料，用于合同与服务管理。</p><div class="form-grid"><div class="field" v-for="f in customerFields" :key="f.label"><label>{{ f.label }} <i v-if="f.required">*</i></label><div class="field-control" :class="{disabled:f.disabled}">{{ f.value }}<a-icon v-if="f.select" type="down" style="margin-left:auto" /></div></div></div><hr class="section-divider"><h2 class="section-title">合同与收款</h2><p class="section-help">请填写合同金额、收款方式等信息。</p><div class="form-grid"><div class="field" v-for="f in contractFields" :key="f.label"><label>{{ f.label }} <i v-if="f.required">*</i></label><div class="field-control" :class="{disabled:f.disabled}">{{ f.value }}<a-icon v-if="f.select" type="down" style="margin-left:auto" /></div></div></div></section>
      <aside class="panel"><div class="panel-head"><div><h2>提交检查</h2><p>请完成以下检查项后提交审核。</p></div></div><div class="check-item" :class="{done:i<2}" v-for="(c,i) in checks" :key="c.title"><span class="check-icon"><a-icon v-if="i<2" type="check" /></span><div><strong>{{ c.title }}</strong><small>{{ c.text }}</small></div></div><div class="warning-box"><strong><a-icon type="exclamation-circle" /> 承诺风险提示</strong><div style="margin-top:8px;color:#8b6a52">请评估服务承诺的履约风险并填写风险说明，以便后续审核。</div></div></aside>
    </div>
  </div>
</template>
<script>
export default { data(){return{steps:['客户信息','合同收款','服务启动','承诺风险','附件确认','状态校验'],customerFields:[{label:'客户主体全称',value:'杭州云启科技有限公司',required:true},{label:'统一社会信用代码',value:'91330106MA2B7C4D9X',required:true},{label:'品牌名',value:'云启科技'},{label:'行业',value:'互联网科技',required:true,select:true},{label:'所在地区',value:'浙江省 / 杭州市 / 西湖区',required:true,select:true},{label:'联系人',value:'张三',required:true},{label:'手机号',value:'13800138000',required:true},{label:'产品类型',value:'SaaS 服务',required:true,select:true}],contractFields:[{label:'合同编号',value:'HT20260801001',required:true},{label:'合同金额',value:'¥ 500,000.00',required:true},{label:'折扣金额',value:'¥ 50,000.00'},{label:'付款方式',value:'银行转账',required:true,select:true},{label:'应收余额',value:'¥ 450,000.00',disabled:true},{label:'付款条款',value:'首付 50%，上线后支付尾款',select:true}],checks:[{title:'客户基本信息',text:'已填写客户主体、联系人等信息'},{title:'合同与收款信息',text:'已填写合同金额、付款方式等信息'},{title:'服务目标设置',text:'请在后续步骤中填写服务目标'},{title:'附件材料',text:'请上传合同、资质等相关附件'}]}}};
</script>
